if (!UnityEngine.Application.isPlaying) throw new System.InvalidOperationException("Play Mode required");
UnityEditor.EditorApplication.isPaused = false;
UnityEditor.SessionState.SetBool("VfxRuntimeDone",false);
var checks = new System.Collections.Generic.List<string>();
System.Action<bool,string> check = (ok,label) => { checks.Add((ok ? "PASS " : "FAIL ") + label); UnityEditor.SessionState.SetString("VfxRuntimeChecks",string.Join("\n",checks)); };
var flags = System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic;
System.Func<object,string,object> get = (o,n) => o.GetType().GetField(n,flags).GetValue(o);
System.Action<object,string,object> set = (o,n,v) => o.GetType().GetField(n,flags).SetValue(o,v);
System.Action<object,string,object[]> call = (o,n,a) => o.GetType().GetMethod(n,flags).Invoke(o,a);
var gm = GameJamKit.GameManager.Instance;
var tutorial = UnityEngine.Object.FindFirstObjectByType<ContextStage.TutorialFlow>(UnityEngine.FindObjectsInactive.Include);
ContextStage.TutorialFlow.SuppressForTests = true;
if (ContextStage.TutorialFlow.IsRunning) call(tutorial,"EndTutorial",new object[]{false,false});
tutorial.enabled = false;
gm.ResetGame();
ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage03.asset"));
gm.StartGame();
ContextStage.AudienceRosterSystem.Instance.SuppressEngagementDecay = true;
ContextStage.PerformanceTimer.SetPaused(true);
var actor = UnityEngine.Object.FindFirstObjectByType<ContextStage.AudienceMemberActor>();
var id = actor.BoundId;
set(actor,"_visibility",1f); set(actor,"_arrivalDelay",0f);
foreach (float value in new[]{33f,25f,15f,5f,1f})
{
    actor.ApplySnapshot(new ContextStage.AudienceSnapshot(id,ContextStage.CrowdPreference.Chill,value,ContextStage.AudienceEngagementStage.Calm,0));
    call(actor,"UpdateWarning",null);
    var fill = (UnityEngine.SpriteRenderer)get(actor,"warningFillRenderer");
    check(fill.gameObject.activeInHierarchy && fill.transform.localScale.x>0 && UnityEngine.Mathf.Abs(fill.transform.localScale.x-value/33f)<0.001f,"warning fraction "+value);
    check(fill.sharedMaterial.shader.name.Contains("Unlit") && fill.color.a==1,"warning unlit "+value);
}
actor.ApplySnapshot(new ContextStage.AudienceSnapshot(id,ContextStage.CrowdPreference.Mosh,70,ContextStage.AudienceEngagementStage.Excited,0));
call(actor,"ResetCardMotion",null); call(actor,"ApplyTransform",null);
var rest = actor.transform.localPosition;
actor.PlayCardMotion("open_mosh_pit",25,rest.x-2,rest.x-4,rest.x+4,UnityEngine.Time.time);
set(actor,"_cardMotionRemaining",0.55f); call(actor,"ApplyTransform",null);
check(UnityEngine.Mathf.Abs(actor.transform.localPosition.x-rest.x)>0.8f,"mosh group spread enlarged");
actor.PlayCardMotion("open_mosh_pit",-5); call(actor,"ApplyTransform",null);
check(UnityEngine.Vector3.Distance(rest,actor.transform.localPosition)<0.001f,"negative response clears gesture");
actor.PlayCardMotion("tempo_up",8);set(actor,"_cardMotionRemaining",0.78f);call(actor,"ApplyTransform",null);
check(UnityEngine.Mathf.Abs(actor.transform.localPosition.x-rest.x)<0.3f && actor.transform.localScale.y>0,"Chill restrained beat");
actor.PlayCardMotion("hands_up",8,0,-4,4,UnityEngine.Time.time);
check((float)get(actor,"_gestureDelay")>=0 && (float)get(actor,"_gestureDelay")<=0.25f,"Singalong stagger bounded");
actor.ReactionVFX.PlayChillBeat(); actor.ReactionVFX.PlayProtection(); actor.ReactionVFX.PlaySingalongGesture();actor.ReactionVFX.PlayMoshLanding();
check(actor.ReactionVFX.HasLiveParticles,"gesture VFX emitted");
actor.ReactionVFX.ResetVisual(); check(!actor.ReactionVFX.HasLiveParticles,"gesture VFX pool reset");
var rain = UnityEngine.Object.FindFirstObjectByType<ContextStage.RainShowerRule>();
var rainVfx = rain.GetComponent<ContextStage.RainShowerVFX>();
check(rainVfx!=null,"rain attached to existing rule");
// Test-only: bypass random special request timing, not production rules.
typeof(ContextStage.StageEventRule).GetField("waitForSpecialRequest",flags).SetValue(rain,false);
check(rain.DebugTriggerNow(),"real rain event begins");
float before = actor.Snapshot.Engagement;
GameJamKit.EventBus.Raise(new GameJamKit.CardResolved{TargetPreference=ContextStage.CrowdPreference.Chill,CrowdReaction=ContextStage.CrowdReactionGrade.Weak});
check(!actor.ReactionVFX.HasLiveParticles,"failed umbrella does not emit protection");
GameJamKit.EventBus.Raise(new GameJamKit.CardResolved{TargetPreference=ContextStage.CrowdPreference.Chill,CrowdReaction=ContextStage.CrowdReactionGrade.Good});
check(actor.ReactionVFX.HasLiveParticles,"actual umbrella recovery emits protection");
set(rainVfx,"_emission",60f);call(rainVfx,"Update",null);
check(rainVfx.ParticleCount>0 && rainVfx.ParticleCount<=108,"bounded two-layer rain and floor splashes");
gm.Pause();float rainAlpha=(float)get(rainVfx,"_alpha");call(rainVfx,"Update",null);
check((float)get(rainVfx,"_alpha")==rainAlpha,"pause freezes rain emission");gm.Resume();
ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage05Boss.asset"));
check(rainVfx.ParticleCount==0 && !rain.IsEventActive,"stage change cancels rain and particles");
var rival = UnityEngine.Object.FindFirstObjectByType<ContextStage.RivalStagePlaceholder>();
int rosterCount=ContextStage.AudienceRosterSystem.Instance.Count;
foreach(var pair in new[]{new{count=6,expected=ContextStage.AudienceEngagementStage.Calm},new{count=10,expected=ContextStage.AudienceEngagementStage.Middle},new{count=16,expected=ContextStage.AudienceEngagementStage.Excited},new{count=6,expected=ContextStage.AudienceEngagementStage.Calm}})
{
    GameJamKit.EventBus.Raise(new ContextStage.BossFanBalanceChanged(20-pair.count,pair.count,20,false));
    check(rival.AudienceStage==pair.expected,"boss shared HP state "+pair.count);
}
check(ContextStage.AudienceRosterSystem.Instance.Count==rosterCount,"display HP events do not mutate real roster");
check(rival.GetComponentsInChildren<ContextStage.AudienceMemberActor>(true).Length==0,"no individual rival actor/HP/bar");
var show = UnityEngine.Object.FindFirstObjectByType<ContextStage.StageShowDirector>();
var rig = UnityEngine.Object.FindObjectsByType<ContextStage.StageLightingRig>(UnityEngine.FindObjectsSortMode.None).First(r=>r.Profile.rival);
var lasers = (ContextStage.PixelLaserRenderer[])get(rig,"lasers");
System.Func<int> active = ()=>lasers.Count(l=>l.GetComponent<UnityEngine.MeshRenderer>().enabled);
rig.Render(5,1,false,true,"drop",false,false,false,true,0,0,false,null,null,0,13,1);
check(active()==0,"last preview frame does NOT open lasers");
rig.Render(5,1,false,false,"drop",false,false,false,true,0,0,false,null,null,0,13,-1,0.15f);
check(active()==8,"pattern start opens 8 lasers");
float opened = lasers[6].transform.localEulerAngles.z;
rig.Render(5,1,false,false,"drop",false,false,false,true,0,0,false,null,null,0,13,-1,1);
check(active()==6,"active drop sustains 6 lasers");
rig.Render(5,1,false,false,null,false,false,false,true,0,0,false,null,null,0,13,-1,1,0.3f);
check(active()==6,"recovery keeps fan until fade completes");
rig.Render(5,1,true,false,"drop",true,true,false,true,1,1,false,null,null,0,13,-1,0.15f);
check(active()==0 && rig.ParticleCount==0,"blackout overrides drop/Fever");
GameJamKit.EventBus.Raise(new ContextStage.BossPatternStarted("drop","DROP","test",5,false));
check(show.DropAge==0,"real pattern event starts drop cue");
gm.Pause();call(show,"LateUpdate",null);check(show.DropAge==0,"pause freezes drop cue");gm.Resume();
gm.ResetGame();
check(show.DropAge<0 && ContextStage.BossCameraDirector.RivalViewBlend==0,"restart resets drop and camera tint");
UnityEditor.SessionState.SetBool("VfxRuntimeDone",true);
return new {pass=checks.Count(x=>x.StartsWith("PASS")),fail=checks.Count(x=>x.StartsWith("FAIL")),checks};
