if(!UnityEngine.Application.isPlaying)throw new System.InvalidOperationException("Play Mode required");
UnityEditor.EditorApplication.isPaused=false;
var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
var checks=new System.Collections.Generic.List<string>();
System.Action<bool,string> check=(ok,n)=>checks.Add((ok?"PASS ":"FAIL ")+n);
var gm=GameJamKit.GameManager.Instance;gm.ResetGame();
var manager=ContextStage.TourRunManager.Instance;
// Standalone Main has no TourPrototypeUI; reproduce its exact presentation-only bootstrap.
var view=manager.GetComponent<ContextStage.DeckAcquisitionFeedback>();
if(view==null)view=manager.gameObject.AddComponent<ContextStage.DeckAcquisitionFeedback>();
view.ConfigureFont(UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.Font>("Assets/Font/DungGeunMo.ttf"));
var stages=new[]{UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage01.asset"),UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage02.asset")};
check(manager.StartNewRun(stages,1028),"new isolated run");
check((float)view.GetType().GetField("_remaining",flags).GetValue(view)==0,"fresh run has no acquisition toast");
check(manager.SelectNode(manager.CurrentRun.map.nodes.First(x=>x.status==ContextStage.RunNodeStatus.Available).nodeId),"select first node");
check(manager.CompleteDialogue(),"dialogue complete");
var node=manager.CurrentRun.CurrentNode;
check(manager.ReceiveStageResult(new ContextStage.StageResult {nodeId=node.nodeId,stageId=node.stageId,cleared=true,score=5000}),"performance result accepted");
check(manager.ConfirmResult(),"reward phase");
var definition=ContextStage.AugmentCatalog.LoadDefault().Definitions.First(x=>x.EffectType==ContextStage.AugmentEffectType.GrantCard && x.Tiers.Any(t=>t.Enabled&&t.GrantedCard!=null));
var tier=definition.Tiers.First(t=>t.Enabled&&t.GrantedCard!=null);
check(manager.SelectAugment(definition.AugmentId,tier.Tier),"existing GrantCard logic succeeds");
check(manager.CurrentRun.deck.addedCards.Count==1,"exactly one real card granted");
var label=(UnityEngine.UI.Text)view.GetType().GetField("_label",flags).GetValue(view);
check(label!=null&&label.text.Contains("덱에 추가됨")&&label.text.Contains(tier.GrantedCard.DisplayName),"actual applied run triggers card toast");
check((float)view.GetType().GetField("_remaining",flags).GetValue(view)>0,"acquisition animation active");
var canvas=(UnityEngine.Canvas)view.GetType().GetField("_canvas",flags).GetValue(view);
check(!canvas.GetComponent<UnityEngine.UI.GraphicRaycaster>().enabled && canvas.GetComponentsInChildren<UnityEngine.UI.Graphic>().All(x=>!x.raycastTarget),"acquisition UI never blocks input");
check(label.font.name=="DungGeunMo","Korean font preserved");
view.GetType().GetMethod("OnRunChanged",flags).Invoke(view,null);
check(manager.CurrentRun.deck.addedCards.Count==1,"notification replay never grants cards");
view.enabled=false;view.enabled=true;
check((float)view.GetType().GetField("_remaining",flags).GetValue(view)==0,"restored run does not replay acquisition");
manager.ResetRun();
check((float)view.GetType().GetField("_remaining",flags).GetValue(view)==0,"new run/reset clears acquisition UI");
return new {pass=checks.Count(x=>x.StartsWith("PASS")),fail=checks.Count(x=>x.StartsWith("FAIL")),checks};
