UnityEditor.EditorApplication.isPaused=false;
var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
var director=UnityEngine.Object.FindFirstObjectByType<ContextStage.StageShowDirector>();
var hint=UnityEngine.Object.FindFirstObjectByType<ContextStage.StageLightController>();
var gm=GameJamKit.GameManager.Instance;
gm.ResetGame();
ContextStage.TutorialFlow.SuppressForTests=true;
ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage02.asset"));
gm.StartGame();ContextStage.PerformanceTimer.SetPaused(true);
System.Action<string,object> set=(name,value)=>director.GetType().GetField(name,flags).SetValue(director,value);
System.Func<string,float> get=name=>(float)director.GetType().GetField(name,flags).GetValue(director);
System.Action update=()=>director.GetType().GetMethod("LateUpdate",flags).Invoke(director,null);
var result=new System.Collections.Generic.List<string>();
hint.SetHeatStage(ContextStage.HeatStage.Chill,true);set("_time",10f);set("_showAge",1f);update();
result.Add("initial no wash cue="+(get("_washStart")==-100));
hint.SetHeatStage(ContextStage.HeatStage.Mosh,true);set("_time",14f);update();
float triggered=get("_washStart");result.Add("discrete hint change cues wash="+(triggered>=14));
hint.SetHeatStage(ContextStage.HeatStage.Singalong,true);set("_time",15f);update();
result.Add("cooldown preserved="+(get("_washStart")==triggered));
hint.SetBlackout(true);update();result.Add("blackout cancels wash="+(get("_washStart")==-100));
hint.SetBlackout(false);
gm.ResetGame();
ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage04.asset"));
gm.StartGame();ContextStage.PerformanceTimer.SetPaused(true);
set("_time",20f);GameJamKit.EventBus.Raise(new GameJamKit.CardResolved{CardId="guitar_solo"});set("_time",20.4f);update();
var rims=UnityEngine.Object.FindObjectsByType<ContextStage.BandRimLightView>(UnityEngine.FindObjectsSortMode.None);
foreach(var rim in rims)rim.GetType().GetMethod("LateUpdate",flags).Invoke(rim,null);
result.Add("all active band rims visible="+rims.All(r=>r.transform.Find("[Band Rim Light]").GetComponent<UnityEngine.SpriteRenderer>().enabled));
set("_time",22f);update();foreach(var rim in rims)rim.GetType().GetMethod("LateUpdate",flags).Invoke(rim,null);
result.Add("all rims finish="+rims.All(r=>!r.transform.Find("[Band Rim Light]").GetComponent<UnityEngine.SpriteRenderer>().enabled));
gm.ResetGame();return result.ToArray();
