if (!UnityEngine.Application.isPlaying) throw new System.InvalidOperationException("Play Mode required");
var checks = new System.Collections.Generic.List<string>();
System.Action<bool,string> check = (ok,label) => checks.Add((ok ? "PASS " : "FAIL ") + label);
var flags = System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic;
System.Func<object,string,object> get = (obj,name) => obj.GetType().GetField(name,flags).GetValue(obj);
System.Action<object,string,object> set = (obj,name,value) => obj.GetType().GetField(name,flags).SetValue(obj,value);
System.Action<object,string,object[]> call = (obj,name,args) => obj.GetType().GetMethod(name,flags).Invoke(obj,args);
var gm = GameJamKit.GameManager.Instance;
var tutorial = UnityEngine.Object.FindFirstObjectByType<ContextStage.TutorialFlow>(UnityEngine.FindObjectsInactive.Include);
ContextStage.TutorialFlow.SuppressForTests = true;
if (ContextStage.TutorialFlow.IsRunning) call(tutorial,"EndTutorial",new object[]{false,false});
tutorial.enabled = true;
gm.ResetGame();
ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage01.asset"));
gm.StartGame();
set(tutorial,"_pendingStartAt",-1f);
check(!(bool)get(tutorial,"compactExperience"),"default tutorial preserved");
tutorial.StartTutorial();
check(ContextStage.TutorialFlow.IsRunning,"manual tutorial active");
check(!ContextStage.FeverSystem.Instance.IsActive,"no early Fever");
check(!ContextStage.FeverSystem.Instance.AutomaticTriggerEnabled,"automatic Fever gated before lesson");
check((float)get(tutorial,"hoverInspectionDuration") == 2f,"Hover remains 2 seconds");
check((float)get(tutorial,"finalDuration") == 10f && (int)get(tutorial,"finalScoreGoal") == 1000,"mini performance 10s/1000");
call(tutorial,"EnterCrossUse",null);
GameJamKit.EventBus.Raise(new GameJamKit.CardResolved { Role=ContextStage.CardRole.Normal,RawAudienceScore=7,GainedScore=84 });
check(get(tutorial,"_phase").ToString()=="CrossExplain","full flow has explanation");
var overlay = UnityEngine.Object.FindFirstObjectByType<ContextStage.TutorialOverlayUI>(UnityEngine.FindObjectsInactive.Include);
var sub = (UnityEngine.UI.Text)get(overlay,"subText");
check(sub.text.Contains("+7") && sub.text.Contains("+84"),"raw reactions and final score distinguished");
set(tutorial,"compactExperience",true);
call(tutorial,"EnterCrossUse",null);
GameJamKit.EventBus.Raise(new GameJamKit.CardResolved { Role=ContextStage.CardRole.Normal,RawAudienceScore=7,GainedScore=84 });
check(get(tutorial,"_phase").ToString()=="Excitement","compact skips explanation into action");
var hand = ContextStage.CardSystem.Instance;
int chill=-1, wrong=-1;
for (int i=0;i<hand.HandCount;i++) { if(hand.GetCard(i).TargetPreference==ContextStage.CrowdPreference.Chill) chill=i;else wrong=i; }
check(chill>=0,"fixed Chill card guaranteed");
var input=UnityEngine.Object.FindFirstObjectByType<ContextStage.CardInput>();
int score=gm.Score, count=hand.HandCount;
var ids=new System.Collections.Generic.List<int>();for(int i=0;i<count;i++)ids.Add(hand.GetCard(i).GetInstanceID());
check(wrong>=0 && !input.TryUseCard(wrong),"wrong tutorial card rejected");
check(gm.Score==score && hand.HandCount==count && Enumerable.Range(0,count).All(i=>hand.GetCard(i).GetInstanceID()==ids[i]),"rejected card not consumed, no score");
GameJamKit.EventBus.Raise(new GameJamKit.CardResolved {Role=ContextStage.CardRole.Normal});
check(get(tutorial,"_phase").ToString()=="CrowdChange","compact merges game-over explanation");
call(tutorial,"EnterFinalIntro",null);
check(sub.text.Contains("1,000") || ((UnityEngine.UI.Text)get(overlay,"mainText")).text.Contains("1,000"),"goal text matches 1000");
call(tutorial,"EndTutorial",new object[]{false,false});
set(tutorial,"compactExperience",false);
check(!ContextStage.TutorialFlow.IsRunning && ContextStage.CardInput.UseFilter==null && ContextStage.CardInput.RequestFilter==null,"tutorial gates restored");
tutorial.enabled=false;
ContextStage.AudienceRosterSystem.Instance.SuppressEngagementDecay=true;
ContextStage.PerformanceTimer.SetPaused(true);
var actor=UnityEngine.Object.FindFirstObjectByType<ContextStage.AudienceMemberActor>();
set(actor,"_visibility",1f); set(actor,"_arrivalDelay",0f);
call(actor,"ResetCardMotion",null);call(actor,"ApplyTransform",null);
var baseline=actor.transform.localPosition;
actor.PlayCardMotion("open_mosh_pit",25);
set(actor,"_cardMotionRemaining",0.45f);call(actor,"ApplyTransform",null);
check(UnityEngine.Mathf.Abs(actor.transform.localPosition.x-baseline.x)>0.3f,"positive mosh spread composed");
actor.PlayCardMotion("open_mosh_pit",-5);call(actor,"ApplyTransform",null);
check(UnityEngine.Vector3.Distance(actor.transform.localPosition,baseline)<0.001f,"negative reaction clears positive gesture");
actor.PlayCardMotion("pass_mic",8);set(actor,"_cardMotionRemaining",0.45f);call(actor,"ApplyTransform",null);
check(actor.transform.localPosition.y>baseline.y+0.1f,"pass mic positive shared bounce");
actor.PlayExit(ContextStage.AudienceExitStyle.RivalStage,null);
check((float)get(actor,"_cardMotionRemaining")==0f,"exit clears reaction motion");
set(actor,"_visibility",0.5f);call(actor,"ApplyTransform",null);
check(actor.transform.localPosition.y>baseline.y+1f,"boss departure moves toward rival");
actor.OnDespawned();actor.OnSpawned();
check((float)get(actor,"_cardMotionRemaining")==0f && !actor.IsBound,"pool reuse clears motion and binding");
var clock=UnityEngine.Object.FindFirstObjectByType<ContextStage.PerformanceTimerUI>();
var baseScale=clock.transform.localScale;
set(clock,"_remaining",4f);call(clock,"Update",null);
check(clock.transform.localScale.x>=baseScale.x,"urgent clock scale pulse");
set(clock,"_remaining",25f);call(clock,"Update",null);
check(UnityEngine.Vector3.Distance(clock.transform.localScale,baseScale)<0.001f,"clock warning clears after extension");
set(clock,"_remaining",4f);call(clock,"Update",null);
call(clock,"OnTimeExtended",new object[]{new ContextStage.PerformanceTimeExtended(5f)});
check((bool)get(clock,"_pulsing"),"existing extension VFX retained");
call(clock,"ResetExtensionVisual",null);
check(UnityEngine.Vector3.Distance(clock.transform.localScale,baseScale)<0.001f,"clock cleanup restores authored scale");
gm.ResetGame();
return new { pass=checks.Count(x=>x.StartsWith("PASS")),fail=checks.Count(x=>x.StartsWith("FAIL")),checks=checks.ToArray() };
