if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Play required");
UnityEditor.EditorApplication.isPaused=false;
var flags=System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance;
var flow=UnityEngine.Object.FindFirstObjectByType<ContextStage.TutorialFlow>();if(flow!=null)flow.enabled=false;
var gm=GameJamKit.GameManager.Instance;var ui=GameJamKit.UIManager.Instance;
ui.CloseAll();gm.ResetGame();
ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage04.asset"));
gm.StartGame();ContextStage.PerformanceTimer.SetPaused(true);
var runner=UnityEngine.Object.FindFirstObjectByType<ContextStage.TourDebugInput>();
runner.StopAllCoroutines();
UnityEditor.SessionState.SetString("BossCameraPauseVerification","running");
var checks=new System.Collections.Generic.List<string>();
void Check(bool ok,string name){checks.Add((ok?"PASS ":"FAIL ")+name);UnityEditor.SessionState.SetString("BossCameraPauseVerification",Newtonsoft.Json.JsonConvert.SerializeObject(new{checks}));}
var keyboard=UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Keyboard>("PauseVerificationKeyboard");
void Key(bool down)=>UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,down?new UnityEngine.InputSystem.LowLevel.KeyboardState(UnityEngine.InputSystem.Key.Escape):new UnityEngine.InputSystem.LowLevel.KeyboardState());
System.Collections.IEnumerator Esc(){Key(true);yield return null;Key(false);yield return new UnityEngine.WaitForSecondsRealtime(.4f);}
System.Collections.IEnumerator Test(){
 yield return new UnityEngine.WaitForSecondsRealtime(.5f);
 var view=UnityEngine.Object.FindFirstObjectByType<ContextStage.StageBackgroundView>();
 Check(view.EditorBaseRenderer.sprite.name=="ST04_BG_Base","Stage 4 uses restored base sprite");
 var pause=ui.Get<ContextStage.PausePopup>();var options=ui.Get<ContextStage.OptionsPopup>();
 yield return Esc();
 Check(pause.IsOpen&&gm.State==GameJamKit.GameState.Paused,"ESC opens pause and pauses game");
 Check(!options.IsOpen&&!options.gameObject.activeSelf,"options invisible on ESC pause");
 ui.OpenOptions();yield return new UnityEngine.WaitForSecondsRealtime(.3f);
 var menu=pause.transform.Find("Buttons").GetComponent<UnityEngine.CanvasGroup>();
 Check(options.IsOpen&&options.GetComponent<UnityEngine.CanvasGroup>().alpha>.99f,"options fully visible");
 Check(menu.alpha==0&&!menu.blocksRaycasts,"pause buttons hidden behind options");
 Check(options.GetComponent<UnityEngine.Canvas>().sortingOrder>pause.GetComponent<UnityEngine.Canvas>().sortingOrder,"options above pause blur");
 yield return Esc();
 Check(!options.IsOpen&&pause.IsOpen&&gm.State==GameJamKit.GameState.Paused,"ESC closes only options, retains pause");
 Check(menu.alpha==1&&menu.blocksRaycasts,"pause menu restored after options fade");
 yield return Esc();
 Check(!pause.IsOpen&&gm.State==GameJamKit.GameState.Playing,"second ESC resumes game");
 ui.Open<ContextStage.PausePopup>();yield return new UnityEngine.WaitForSecondsRealtime(.3f);
 ui.OpenOptions();yield return new UnityEngine.WaitForSecondsRealtime(.3f);
 options.CloseImmediate();
 Check(menu.alpha==1,"immediate options close restores menu");
 pause.CloseImmediate();
 gm.ResetGame();
 ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage05Boss.asset"));
 gm.StartGame();ContextStage.PerformanceTimer.SetPaused(true);
 var boss=UnityEngine.Object.FindFirstObjectByType<ContextStage.BossStagePresentation>();
 yield return new UnityEngine.WaitForSecondsRealtime(.5f);
 var button=(UnityEngine.UI.Button)boss.GetType().GetField("_peekButton",flags).GetValue(boss);
 Check(button!=null&&button.image.sprite!=null&&button.image.sprite.name=="boss_camera","boss camera image button uses asset");
 Check(button.image.preserveAspect&&button.interactable,"camera aspect preserved and clickable");
 var pointer=new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current){position=UnityEngine.RectTransformUtility.WorldToScreenPoint(null,button.transform.position)};
 var hits=new System.Collections.Generic.List<UnityEngine.EventSystems.RaycastResult>();
 UnityEngine.EventSystems.EventSystem.current.RaycastAll(pointer,hits);
 Check(hits.Count>0&&hits[0].gameObject==button.gameObject,"camera button is top pointer hit");
 UnityEngine.EventSystems.ExecuteEvents.Execute(button.gameObject,pointer,UnityEngine.EventSystems.ExecuteEvents.pointerClickHandler);
 yield return new UnityEngine.WaitForSeconds(2f);
 var camera=boss.GetComponent<ContextStage.BossCameraDirector>();
 Check(boss.IsPeeking&&camera.CurrentZone==ContextStage.BossZone.RivalStage,"pointer click pans to rival");
 ui.Open<ContextStage.PausePopup>();yield return new UnityEngine.WaitForSecondsRealtime(.3f);
 bool peeking=boss.IsPeeking;boss.TogglePeek();
 Check(boss.IsPeeking==peeking&&!button.interactable,"camera blocked while paused");
 pause.CloseImmediate();yield return null;
 UnityEngine.EventSystems.ExecuteEvents.Execute(button.gameObject,pointer,UnityEngine.EventSystems.ExecuteEvents.pointerClickHandler);
 yield return new UnityEngine.WaitForSeconds(2f);
 Check(!boss.IsPeeking&&camera.CurrentZone==ContextStage.BossZone.OurStage,"second click returns to our stage");
 UnityEngine.InputSystem.InputSystem.RemoveDevice(keyboard);
 UnityEditor.SessionState.SetString("BossCameraPauseVerification",Newtonsoft.Json.JsonConvert.SerializeObject(new{pass=checks.Count(x=>x.StartsWith("PASS")),fail=checks.Count(x=>x.StartsWith("FAIL")),checks}));
 UnityEditor.EditorApplication.isPaused=true;
}
runner.StartCoroutine(Test());return "ESC/popup, Stage4 and camera pointer verification started";
