if (!UnityEngine.Application.isPlaying) throw new System.Exception("Play mode required");
UnityEditor.EditorApplication.isPaused=false;
var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
object Read(object o,string name)=>o.GetType().GetField(name,flags).GetValue(o);
void Call(object o,string name)=>o.GetType().GetMethod(name,flags).Invoke(o,null);
var checks=new System.Collections.Generic.List<string>();
void Check(bool pass,string name){if(!pass)throw new System.Exception("FAIL: "+name);checks.Add(name);}
ContextStage.TutorialFlow.SuppressForTests=true;
var tutorial=UnityEngine.Object.FindFirstObjectByType<ContextStage.TutorialFlow>();tutorial.enabled=false;
var overlay=UnityEngine.Object.FindFirstObjectByType<ContextStage.TutorialOverlayUI>();overlay.HideAll();
var gm=GameJamKit.GameManager.Instance;gm.ResetGame();
var runtime=ContextStage.StageRuntimeDirector.Active;
var bossStage=UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage05Boss.asset");
runtime.ApplyStage(bossStage);gm.StartGame();
foreach(var rule in UnityEngine.Object.FindObjectsByType<ContextStage.StageEventRule>(UnityEngine.FindObjectsSortMode.None)) rule.enabled=false;
UnityEngine.Object.FindFirstObjectByType<ContextStage.BossBattleRule>().enabled=false;
ContextStage.PerformanceTimer.SetPaused(true);
ContextStage.AudienceRosterSystem.Instance.SuppressEngagementDecay=true;
var boss=UnityEngine.Object.FindFirstObjectByType<ContextStage.BossBattleUI>();
var notice=UnityEngine.Object.FindFirstObjectByType<ContextStage.StageEventNoticeUI>();
GameJamKit.EventBus.Raise(new ContextStage.BossFanBalanceChanged(14,6,20,false));
var panel=(UnityEngine.RectTransform)Read(boss,"_patternPanel");
var view=panel.GetComponent<ContextStage.MissionCueSheetView>();
Check(panel.anchorMin==new UnityEngine.Vector2(0,.5f),"boss mission left-middle anchor");
Check(panel.anchoredPosition==new UnityEngine.Vector2(32,0),"boss mission offset");
var bar=((UnityEngine.UI.Image)Read(boss,"_barBack")).rectTransform;
Check(bar.anchorMin==new UnityEngine.Vector2(.5f,1)&&bar.sizeDelta==new UnityEngine.Vector2(900,26),"fan gauge unchanged");
Check(view.GetComponent<UnityEngine.UI.Image>().sprite.name=="MissionSlate","independent slate resource");
GameJamKit.EventBus.Raise(new ContextStage.StageEventStarted("stadium_contested_fan","스탠딩석 팬 쟁탈","SINGALONG 카드로 좋은 반응을 이끌어내세요.",8));
Check(view.Title.text=="스탠딩석 팬 쟁탈","standing mission routed");
Check(Read(notice,"_panel")==null||!((UnityEngine.RectTransform)Read(notice,"_panel")).gameObject.activeSelf,"center duplicate suppressed");
GameJamKit.EventBus.Raise(new ContextStage.BossPatternStarted("b2b","B2B","라이벌의 트랙에 답하라 — [무대 장악] 사용!",8,false));
Check(view.Title.text=="B2B"&&view.Secondary.text.Contains("SINGALONG"),"overlapping actionable missions both visible");
Check(panel.sizeDelta.y==368,"dual mission space");
GameJamKit.EventBus.Raise(new ContextStage.StageEventResolved("stadium_contested_fan","스탠딩석 팬 쟁탈",false,"SINGALONG 팬은 라이벌 무대로 갔습니다."));
Check(view.Title.text=="B2B"&&view.Secondary.text.Contains("라이벌 무대로"),"old standing result cannot replace active boss mission");
GameJamKit.EventBus.Raise(new ContextStage.BossPatternProgress("wrong",1,8,"BAD",false));
Check(view.Progress.text!="BAD","stale pattern progress ignored");
GameJamKit.EventBus.Raise(new ContextStage.BossPatternResolved("wrong","BAD",false,0,0,1));
Check(view.Title.text=="B2B","stale pattern result ignored");
GameJamKit.EventBus.Raise(new ContextStage.BossPatternProgress("b2b",7.9f,8,"0 / 1",false));
Check(view.Progress.text=="0 / 1"&&view.Timer.text=="7.9s","matching progress updates");
gm.Pause();Check(!((UnityEngine.Canvas)Read(boss,"_canvas")).gameObject.activeSelf,"boss mission hidden during pause");
gm.Resume();Check(panel.gameObject.activeSelf,"mission restored after pause");
GameJamKit.EventBus.Raise(new ContextStage.BossPatternResolved("b2b","B2B",true,1,500,2));
GameJamKit.EventBus.Raise(new ContextStage.BossPatternStarted("new","새 미션","새 조건",6,false));
var standing=Read(boss,"_standing");standing.GetType().GetField("ResultRemaining").SetValue(standing,.000001f);
Call(boss,"Update");Check(panel.gameObject.activeSelf&&view.Title.text=="새 미션","expired prior result cannot hide new mission");
runtime.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage03.asset"));
Check(!panel.gameObject.activeSelf,"stage change clears boss mission");
GameJamKit.EventBus.Raise(new ContextStage.StageEventStarted("rain_shower","소나기","관객에게 우산을 전달하세요.",8));
var normal=(UnityEngine.RectTransform)Read(notice,"_panel");
Check(normal.gameObject.activeSelf,"ordinary event still displayed");
GameJamKit.EventBus.Raise(new ContextStage.StageEventProgress("other",1,8,"BAD"));
Check(((TMPro.TMP_Text)Read(notice,"_progress")).text!="BAD","unrelated ordinary progress ignored");
Check(normal.GetComponent<UnityEngine.UI.Image>().sprite.name=="MissionSlate","ordinary mission slate");
gm.ResetGame();Check(!normal.gameObject.activeSelf,"ready clears event");
overlay.ShowMessage("관객 위에 마우스를 올리거나 길게 누르면 관객의 마음을 알 수 있습니다.","말풍선과 테두리색을 통해 좋아하는 행동과 현재 기분을 확인할 수 있습니다. 관객을 2초 동안 살펴보세요.",true);
Check(overlay.PanelImage.sprite.name=="TutorialPaper","tutorial independent paper");
var panelBefore=overlay.PanelImage.rectTransform.anchoredPosition;
overlay.SetSpecialLessonLayout(true);overlay.SetSpecialLessonLayout(false);
Check(overlay.PanelImage.rectTransform.anchoredPosition==panelBefore,"special lesson restores hand-placed layout");
Check(((UnityEngine.UI.Text)Read(overlay,"subText")).color==ContextStage.MissionCueSheetView.Ink,"paper dark ink");
var dialogue=UnityEngine.Object.Instantiate(UnityEngine.Resources.Load<UnityEngine.GameObject>("Dialogue/DialoguePanel")).GetComponent<ContextStage.DialoguePanel>();
var sequence=UnityEngine.ScriptableObject.CreateInstance<ContextStage.DialogueSequence>();
sequence.EditorInitialize("test",new System.Collections.Generic.List<ContextStage.DialogueLine>{new ContextStage.DialogueLine{speakerName="너구리",text="짧은 대사"},new ContextStage.DialogueLine{speakerName="너구리",text="긴 대사여도 다음 화살표는 같은 자리에 있어야 합니다. 관객의 마음을 확인하고 공연을 시작합시다."}});
dialogue.Play(sequence,new ContextStage.DialoguePresentationContext(),null);
Call(dialogue,"CompleteLineInstantly");
var arrow=(UnityEngine.UI.Image)Read(dialogue,"arrowImage");var pos=arrow.rectTransform.anchoredPosition;
Check(arrow.enabled&&pos==new UnityEngine.Vector2(-80,42),"short dialogue corner arrow");
dialogue.Advance();Call(dialogue,"CompleteLineInstantly");
Check(arrow.rectTransform.anchoredPosition==pos,"long dialogue same arrow position");
Check(arrow.rectTransform.anchorMin==new UnityEngine.Vector2(1,0)&&arrow.rectTransform.pivot==new UnityEngine.Vector2(1,0),"fixed arrow corner anchors");
UnityEngine.Object.Destroy(dialogue.gameObject);UnityEngine.Object.Destroy(sequence);overlay.HideAll();
return Newtonsoft.Json.JsonConvert.SerializeObject(new{passed=checks.Count,checks});
