if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Play Mode required");
UnityEditor.EditorApplication.isPaused=false;
ContextStage.TutorialFlow.SuppressForTests=true;
var flow=UnityEngine.Object.FindFirstObjectByType<ContextStage.TutorialFlow>();
var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
void Call(string name)=>flow.GetType().GetMethod(name,flags).Invoke(flow,null);
object Read(string name)=>flow.GetType().GetField(name,flags).GetValue(flow);
var gm=GameJamKit.GameManager.Instance;gm.ResetGame();
ContextStage.StageRuntimeDirector.Active.ApplyStage(UnityEditor.AssetDatabase.LoadAssetAtPath<ContextStage.StageDefinition>("Assets/Settings/Tour/Stage01.asset"));gm.StartGame();
flow.StartTutorial();Call("EnterPrefChill");
var roster=ContextStage.AudienceRosterSystem.Instance;
var oldId=roster.Members.First().Id;
Call("EnterHoverHint");
var mouse=UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Mouse>("TutorialVerificationMouse");
var checks=new System.Collections.Generic.List<string>();
void Check(bool ok,string name){checks.Add((ok?"PASS ":"FAIL ")+name);UnityEditor.SessionState.SetString("HoverLessonVerification",Newtonsoft.Json.JsonConvert.SerializeObject(new{pass=checks.Count(x=>x.StartsWith("PASS")),fail=checks.Count(x=>x.StartsWith("FAIL")),checks}));}
void Point(UnityEngine.Vector2 p)=>UnityEngine.InputSystem.InputSystem.QueueStateEvent(mouse,new UnityEngine.InputSystem.LowLevel.MouseState{position=p});
void Target(ContextStage.AudienceMemberActor actor)=>Point(UnityEngine.Camera.main.WorldToScreenPoint(actor.PreferenceHoverCenter));
UnityEditor.SessionState.SetString("HoverLessonVerification","running");
System.Collections.IEnumerator Test(){
 yield return new UnityEngine.WaitForSecondsRealtime(.8f);
 var id=(ContextStage.AudienceId)Read("_inspectionTargetId");
 var actor=(ContextStage.AudienceMemberActor)Read("_inspectionActor");
 Check(id.IsValid&&id!=oldId,"new audience ID");
 var start=actor.transform.localPosition;var sprite=actor.CharacterRenderer.sprite;
 var guide=flow.GetType().GetField("_dragGuide",flags).GetValue(flow) as ContextStage.TutorialDragGuideUI;
 var root=(UnityEngine.RectTransform)guide.GetType().GetField("_root",flags).GetValue(guide);
 var hand=(UnityEngine.RectTransform)guide.GetType().GetField("_hand",flags).GetValue(guide);
 var handStart=hand.anchoredPosition;
 yield return new UnityEngine.WaitForSecondsRealtime(.3f);
 Check(UnityEngine.Vector3.Distance(start,actor.transform.localPosition)<.001f,"target position stable");
 Check(sprite==actor.CharacterRenderer.sprite,"target sprite pose stable");
 Check(UnityEngine.Vector2.Distance(handStart,hand.anchoredPosition)>.1f,"cursor guide animates");
 Check(!root.GetComponent<UnityEngine.CanvasGroup>().blocksRaycasts&&root.GetComponentsInChildren<UnityEngine.UI.Graphic>(true).All(g=>!g.raycastTarget),"guide cannot intercept input");
 Call("OnContinueClicked");Check(Read("_phase").ToString()=="HoverHint","cannot skip required inspection");
 Check(!(bool)flow.GetType().GetMethod("FilterCard",flags).Invoke(flow,new object[]{0}),"cards blocked without consumption during inspection");
 roster.TryAdd(ContextStage.CrowdPreference.Mosh,52,ContextStage.AudienceJoinReason.RuntimeCommand,out var wrong);
 yield return new UnityEngine.WaitForSecondsRealtime(.8f);
 var presenter=UnityEngine.Object.FindFirstObjectByType<ContextStage.AudienceRosterPresenter>();presenter.TryGetActor(wrong.Id,out var wrongActor);
 wrongActor.SetTutorialInspectionPose(true);
 Target(wrongActor);yield return new UnityEngine.WaitForSecondsRealtime(2.6f);
 Check(!(bool)Read("_hoverTaught"),"wrong audience cannot complete lesson");
 Point(new UnityEngine.Vector2(1000,50));yield return new UnityEngine.WaitForSecondsRealtime(.2f);
 Target(actor);yield return new UnityEngine.WaitForSecondsRealtime(1.2f);
 Check(!(bool)Read("_hoverTaught"),"short hover does not complete");
 Point(new UnityEngine.Vector2(1000,50));yield return new UnityEngine.WaitForSecondsRealtime(.2f);
 Check((float)Read("_hoverInspectionTimer")==0,"leaving target resets hold timer");
 Target(actor);yield return new UnityEngine.WaitForSecondsRealtime(2.7f);
 Check((bool)Read("_hoverTaught"),"real Input System hover completes after hold");
 Check(!root.gameObject.activeSelf,"guide hides after completion");
 Call("OnContinueClicked");Check(Read("_phase").ToString()=="CrossUse","continues to cross reaction lesson");
 Check(!(bool)actor.GetType().GetField("_tutorialInspectionPose",flags).GetValue(actor),"inspection pose released at transition");
 Call("EnterCrowdChange");yield return new UnityEngine.WaitForSecondsRealtime(.8f);
 actor=(ContextStage.AudienceMemberActor)Read("_inspectionActor");
 Check(actor!=null&&actor.Snapshot.Preference==ContextStage.CrowdPreference.Singalong,"new SINGALONG target bound for crowd change");
 Check(root.gameObject.activeSelf,"crowd change also shows guide");
 flow.enabled=false;
 Check(!(bool)actor.GetType().GetField("_tutorialInspectionPose",flags).GetValue(actor)&&!root.gameObject.activeSelf,"disable releases pose and guide");
 UnityEngine.InputSystem.InputSystem.RemoveDevice(mouse);
 flow.enabled=true;
 UnityEditor.SessionState.SetString("HoverLessonVerification",Newtonsoft.Json.JsonConvert.SerializeObject(new{pass=checks.Count(x=>x.StartsWith("PASS")),fail=checks.Count(x=>x.StartsWith("FAIL")),checks}));
 UnityEditor.EditorApplication.isPaused=true;
}
flow.StartCoroutine(Test());return "Asynchronous actual Input System hover checks started; no tutorial completion save";
